### ISSUE TITLE
On some systems, text handling gives wrong output for Julia 0.4

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/Cairo.jl#122]
@lobingera When I run your test file, I now get the following output:

![sample_copy_path](https://cloud.githubusercontent.com/assets/52289/10369329/8d829958-6dd1-11e5-868e-b0211d7dba1f.png)

which no longer matches the output in the samples directory. It's as if a recent change broke `Cairo.convert_cairo_path_data(Cairo.copy_path(cr))`. 

    julia> Pkg.status("Cairo")
     - Cairo                         0.2.31

Not sure what happened, though.

**Comment by lobingera** [comment]
unfortunately i cannot reproduce, i get this picture, 
![sample_copy_path](https://cloud.githubusercontent.com/assets/5199059/10372191/013df68e-6de7-11e5-9d9b-0ba115959876.png)
running a v0.4.0-rc4 with Cairo 0.2.31. 

Could it be, that your font selection does something strange? The example just selects 'Sans' and that could be everything depending on your libcairo/libftype2/libpango settings.

**Comment by lobingera** [comment]
You could set the fontsize in line 34 to something reasonable (lower than 100.0) to see how your glyph for "J" looks like.

**Comment by cormullion** [comment]
@lobingera Thanks for looking at this. I was hoping it wasn't going to be my fault, but it looks like something has happened at my end. I'll investigate further, knowing that it's OK elsewhere. (Too many packages updating all the time trying to get everything working with everything else: Homebrew, Images, Colors, Cairo, MacOS X, ...;)

**Comment by cormullion** [comment]
I'll reopen this and leave it, just in case someone else encounters text-handling problems in Julia 0.4/Cairo.

I ran samples/sample_text.jl in both 0.3.11 (left) and 0.4:

![sample_text 0.3.11](https://cloud.githubusercontent.com/assets/52289/10377304/6b79fc7e-6dfa-11e5-9e0b-99f6a7e9122b.png) ![sample_text_0.4](https://cloud.githubusercontent.com/assets/52289/10377308/763f380e-6dfa-11e5-8dea-2f025c484c1f.png)

It's the behavior of `text_path` that's changed on my system. I'm reluctant to delete Julia and re-install, but it might come to that.

**Comment by lobingera** [comment]
As you mention OSX, does homebrew build two local versions of Cairo?

**Comment by cormullion** [comment]
@lobingera There were a few... :) MacPorts has one as well as HomeBrew. I'm doing a clean installation of Julia 0.4.

**Comment by lobingera** [comment]
@cormullion 
btw: have you checked #121?

**Comment by cormullion** [comment]
@lobingera  yes I saw that. Weird.  I had no problems with installing, though...

**Comment by ranma42** [comment]
Can you check the version of cairo you are using?
It looks like it is affected by https://bugs.freedesktop.org/show_bug.cgi?id=84324

**Comment by cormullion** [comment]
I think Julia 0.4.0 currently installs Cairo 1.14.2 via Homebrew:

    ls /Users/me/.julia/v0.4/Homebrew/deps/usr/Cellar/cairo/1.14.2/lib/
     cairo					libcairo-script-interpreter.2.dylib	libcairo.a
     libcairo-gobject.2.dylib		libcairo-script-interpreter.a		libcairo.dylib
     libcairo-gobject.a			libcairo-script-interpreter.dylib	pkgconfig
     libcairo-gobject.dylib			libcairo.2.dylib

Is that issue you linked the same one that generated this message:

    julia[8533] <Error>: The function ‘CGFontGetGlyphPath’ is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.

That must have been fixed, I don't see it anymore. 

This text_path() problem appears on both MacOX 10.10 (Yosemite) and 10.11 (El Capitan) on Julia 0.4.0.

**Comment by ranma42** [comment]
@cormullion I think you missed the part of the bug report about the regression introduced by that patch and the following fix, which is not yet available in a cairo release (see last few comments in the bugzilla thread).
Would you be able to check if cairo 1.14.0 or cairo master have the same problem?
It is very likely that you are seeing this: https://bugs.freedesktop.org/attachment.cgi?id=115677

**Comment by cormullion** [comment]
@ranma ah yes that looks like it! Thanks! I'll investigate how to check other Cairo versions, I usually just hope that the Julia package installer does the right thing when building...

**Comment by ranma42** [comment]
The bug should be fixed in [cairo 1.14.4](http://cairographics.org/news/cairo-1.14.4).

**Comment by cormullion** [comment]
@ranma42 Just downloaded Julia v4.1 and ran Pkg.update(). Cairo is now at 1.14.4, and the text now renders correctly! Yay! Thanks to everyone who did the necessary updating work. Will close this issue.

@lobingera Fyi I ran `samples/sample_text.jl` again after updating everything, and it doesn't appear to have picked up your commits from #123 — I'm still seeing the deprecation and `strftime` warnings which you fixed, which is a bit odd. I would expect the `samples` directory to get refreshed as well.

**Comment by lobingera** [comment]
@cormullion, looks like #123 is available on master, but not in the last release 0.2.31 from 19sept.
